version: '3.9'
services:
  api:
    build: ./backend
    environment:
      - NODE_ENV=production
    volumes:
      - sqlite-data:/app/data
    command: node dist/index.js
    ports:
      - "3000:3000"

  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  sqlite-data: 