name: Deploy Docs
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs (Docsify is static)
        run: |
          cp -r docs public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public 